spring:
  application:
    name: enterprise-testing-app
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    root: INFO
    ua.edu.practice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# Test Configuration
test:
  data:
    orders:
      count: 100
    users:
      count: 50

# JMeter Configuration
jmeter:
  test:
    plan: src/test/jmeter/order-api-test.jmx
    results: target/jmeter/results
    reports: target/jmeter/reports
