services:
  postgres:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks:
      - practice-7
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      retries: 3
      timeout: 5s

volumes:
  postgres:

networks:
  practice-7:
    driver: bridge